In [ ]:
# doing necessary importation
import pandas as pd  # noqa: F401

In [23]:
# load data
df = pd.read_csv(
    "../../1_datasets/data/01_category_war_events_data/food_insecurity_and_violent_conflict_gaza_dataset/fivc_gaza_octobe.csv"
)
df.head()

,ID,Date,Country,Admin 1,Admin 2,Location,Reported Perpetrator Name,Reported Means of Action,Object Affected,Sub-Object Affected,Latitude,Longitude,Geo-Precision,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,"3,070",12/3/2023,occupied Palestinian territories,Gaza Strip,Deir el-Balah,Deir al Balah,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.42,34.35,[2] 25km precision,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"3,071",11/16/2023,occupied Palestinian territories,Gaza Strip,North Gaza,NaN,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.53,34.48,[2] 25km precision,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"3,072",11/1/2023,occupied Palestinian territories,Gaza Strip,Gaza City,NaN,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.54,34.46,[2] 25km precision,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"3,073",10/30/2023,occupied Palestinian territories,Gaza Strip,Khan Younis,Al Amal,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.35,34.29,[2] 25km precision,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"3,074",10/25/2023,occupied Palestinian territories,Gaza Strip,Gaza City,NaN,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.50,34.45,[2] 25km precision,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.shape

(1094, 20)

Removing completely empty rows

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         284 non-null    object
 1   Date                       284 non-null    object
 2   Country                    284 non-null    object
 3   Admin 1                    284 non-null    object
 4   Admin 2                    278 non-null    object
 5   Location                   210 non-null    object
 6   Reported Perpetrator Name  284 non-null    object
 7   Reported Means of Action   284 non-null    object
 8   Object Affected            284 non-null    object
 9   Sub-Object Affected        284 non-null    object
 10  Latitude                   284 non-null    float64
 11  Longitude                  284 non-null    float64
 12  Geo-Precision              284 non-null    object
 13  Unnamed: 13                0 non-null      float64
 14  Unnamed: 14                0 non-null      float64
 15  Unnamed: 15                0 non-null      float64
 16  Unnamed: 16                0 non-null      float64
 17  Unnamed: 17                0 non-null      float64
 18  Unnamed: 18                0 non-null      float64
 19  Unnamed: 19                0 non-null      float64
dtypes: float64(9), object(11)
memory usage: 171.1+ KB

As we see there are columns that completely empty, thats maybe due to excel empty columns

In [26]:
# Calculate how many completely empty row are there:
# df[] to get it in a dataframe
# df.isna() creates a boolean DataFrame of the same shape, with True where values are NaN
# .all() checks if all values in the same row are TRUE (basically isna)
# shape: get dimensions (rows, cols)
df[df.isna().all(axis=1)].shape

(810, 20)

In [27]:
df = df.dropna(how="all")
df.shape

(284, 20)

In [28]:
# get the precentage of null values for each column
# isna() creates a dataframe with T/F value for each cell in the dataframe
# .mean() gets the mean of TRUE values for each column
df.isna().mean() * 100

ID                             0.000000
Date                           0.000000
Country                        0.000000
Admin 1                        0.000000
Admin 2                        2.112676
Location                      26.056338
Reported Perpetrator Name      0.000000
Reported Means of Action       0.000000
Object Affected                0.000000
Sub-Object Affected            0.000000
Latitude                       0.000000
Longitude                      0.000000
Geo-Precision                  0.000000
Unnamed: 13                  100.000000
Unnamed: 14                  100.000000
Unnamed: 15                  100.000000
Unnamed: 16                  100.000000
Unnamed: 17                  100.000000
Unnamed: 18                  100.000000
Unnamed: 19                  100.000000
dtype: float64

dropping completely empty columns

In [29]:
df = df.dropna(axis=1, how="all")
df.shape

(284, 13)

checking null values

In [30]:
df.isna().sum()

ID                            0
Date                          0
Country                       0
Admin 1                       0
Admin 2                       6
Location                     74
Reported Perpetrator Name     0
Reported Means of Action      0
Object Affected               0
Sub-Object Affected           0
Latitude                      0
Longitude                     0
Geo-Precision                 0
dtype: int64

Location and Admin 2 has Nan values
substituting all Nan values in Location and Admin 2 with the word "unknown"

In [31]:
df = df.fillna("unknown")
df
# there is another way : df.fillna('value', inplace = True)

,ID,Date,Country,Admin 1,Admin 2,Location,Reported Perpetrator Name,Reported Means of Action,Object Affected,Sub-Object Affected,Latitude,Longitude,Geo-Precision
0,"3,070",12/3/2023,occupied Palestinian territories,Gaza Strip,Deir el-Balah,Deir al Balah,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.42,34.35,[2] 25km precision
1,"3,071",11/16/2023,occupied Palestinian territories,Gaza Strip,North Gaza,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.53,34.48,[2] 25km precision
2,"3,072",11/1/2023,occupied Palestinian territories,Gaza Strip,Gaza City,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.54,34.46,[2] 25km precision
3,"3,073",10/30/2023,occupied Palestinian territories,Gaza Strip,Khan Younis,Al Amal,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.35,34.29,[2] 25km precision
4,"3,074",10/25/2023,occupied Palestinian territories,Gaza Strip,Gaza City,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.50,34.45,[2] 25km precision
...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,"3,349",7/26/2024,occupied Palestinian territories,Gaza Strip,Gaza City,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Market,31.52,34.46,[2] 25km precision
280,"3,350",7/24/2024,occupied Palestinian territories,Gaza Strip,Khan Younis,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Market,31.34,34.30,[2] 25km precision
281,"3,351",7/9/2024,occupied Palestinian territories,Gaza Strip,Deir el-Balah,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Market,31.45,34.39,[2] 25km precision
282,"3,352",6/9/2024,occupied Palestinian territories,Gaza Strip,Gaza City,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Market,31.50,34.47,[2] 25km precision
283,"3,353",5/26/2024,occupied Palestinian territories,Gaza Strip,Rafah,unknown,Armed Forces of Israel,"Artillery, Shelling or Missile Fire",Food Supply Chains,Market,31.26,34.28,[2] 25km precision

check that there is no more Nan values

In [32]:
df.isnull().sum()

ID                           0
Date                         0
Country                      0
Admin 1                      0
Admin 2                      0
Location                     0
Reported Perpetrator Name    0
Reported Means of Action     0
Object Affected              0
Sub-Object Affected          0
Latitude                     0
Longitude                    0
Geo-Precision                0
dtype: int64

check  Admin 2 column

In [33]:
df["Admin 2"].value_counts()

Admin 2
Deir el-Balah                76
Gaza City                    68
Rafah                        58
Khan Younis                  44
North Gaza                   26
unknown                       6
Rafah                         3
Deir al-Balah Governorate     2
Gaza Governorate              1
Name: count, dtype: int64

we have:

* two Rafah
* Gaza city is the same as Gaza Governorate
* Deir el-Balah is the same as Deir al-Balah Governorate

so we are going to use replace method in pandas

In [34]:
df.replace(
    {
        "Admin 2": {
            "Rafah ": "Rafah",
            "Gaza Governorate": "Gaza City",
            "Deir al-Balah Governorate": "Deir el-Balah",
        },
    },
    inplace=True,
)

df

,ID,Date,Country,Admin 1,Admin 2,Location,Reported Perpetrator Name,Reported Means of Action,Object Affected,Sub-Object Affected,Latitude,Longitude,Geo-Precision
0,"3,070",12/3/2023,occupied Palestinian territories,Gaza Strip,Deir el-Balah,Deir al Balah,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.42,34.35,[2] 25km precision
1,"3,071",11/16/2023,occupied Palestinian territories,Gaza Strip,North Gaza,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.53,34.48,[2] 25km precision
2,"3,072",11/1/2023,occupied Palestinian territories,Gaza Strip,Gaza City,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.54,34.46,[2] 25km precision
3,"3,073",10/30/2023,occupied Palestinian territories,Gaza Strip,Khan Younis,Al Amal,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.35,34.29,[2] 25km precision
4,"3,074",10/25/2023,occupied Palestinian territories,Gaza Strip,Gaza City,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.50,34.45,[2] 25km precision
...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,"3,349",7/26/2024,occupied Palestinian territories,Gaza Strip,Gaza City,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Market,31.52,34.46,[2] 25km precision
280,"3,350",7/24/2024,occupied Palestinian territories,Gaza Strip,Khan Younis,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Market,31.34,34.30,[2] 25km precision
281,"3,351",7/9/2024,occupied Palestinian territories,Gaza Strip,Deir el-Balah,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Market,31.45,34.39,[2] 25km precision
282,"3,352",6/9/2024,occupied Palestinian territories,Gaza Strip,Gaza City,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Market,31.50,34.47,[2] 25km precision
283,"3,353",5/26/2024,occupied Palestinian territories,Gaza Strip,Rafah,unknown,Armed Forces of Israel,"Artillery, Shelling or Missile Fire",Food Supply Chains,Market,31.26,34.28,[2] 25km precision

check Admin 2 value count again

In [35]:
df["Admin 2"].value_counts()

Admin 2
Deir el-Balah    78
Gaza City        69
Rafah            61
Khan Younis      44
North Gaza       26
unknown           6
Name: count, dtype: int64

getting information about the data and the type of the values

In [36]:
df.info()
# you can use df.dtypes()

<class 'pandas.core.frame.DataFrame'>
Index: 284 entries, 0 to 283
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         284 non-null    object
 1   Date                       284 non-null    object
 2   Country                    284 non-null    object
 3   Admin 1                    284 non-null    object
 4   Admin 2                    284 non-null    object
 5   Location                   284 non-null    object
 6   Reported Perpetrator Name  284 non-null    object
 7   Reported Means of Action   284 non-null    object
 8   Object Affected            284 non-null    object
 9   Sub-Object Affected        284 non-null    object
 10  Latitude                   284 non-null    float64
 11  Longitude                  284 non-null    float64
 12  Geo-Precision              284 non-null    object
dtypes: float64(2), object(11)
memory usage: 31.1+ KB

after checking we can see that the date must be changed to type datetime instead of type object

In [37]:
# Fix the date format manually
df["Date"] = df["Date"].replace("28-10-2023", "10/28/2023")


# converting  the column
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [38]:
# check
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 284 entries, 0 to 283
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         284 non-null    object
 1   Date                       284 non-null    datetime64[ns]
 2   Country                    284 non-null    object
 3   Admin 1                    284 non-null    object
 4   Admin 2                    284 non-null    object
 5   Location                   284 non-null    object
 6   Reported Perpetrator Name  284 non-null    object
 7   Reported Means of Action   284 non-null    object
 8   Object Affected            284 non-null    object
 9   Sub-Object Affected        284 non-null    object
 10  Latitude                   284 non-null    float64
 11  Longitude                  284 non-null    float64
 12  Geo-Precision              284 non-null    object
dtypes: datetime64[ns](1), float64(2), object(10)
memory usage: 31.1+ KB

checking if there is any empty cells in the Date column after converting its type

In [39]:
df[df["Date"].isna()]

Empty DataFrame
Columns: [ID, Date, Country , Admin 1, Admin 2, Location, Reported Perpetrator Name, Reported Means of Action, Object Affected, Sub-Object Affected, Latitude, Longitude, Geo-Precision]
Index: []

good converted with no problems, now we will sort the messy dates so that we can see the events from the oldest to the newest

In [40]:
df = df.sort_values(by="Date", ascending=True)
df

,ID,Date,Country,Admin 1,Admin 2,Location,Reported Perpetrator Name,Reported Means of Action,Object Affected,Sub-Object Affected,Latitude,Longitude,Geo-Precision
166,"3,236",2023-10-07,occupied Palestinian territories,Gaza Strip,Gaza City,Sheikh Radwan,Armed Forces of Israel,Air or Drone Strike,Crops and Lands,Agricultural Land,31.53,34.47,[2] 25km precision
165,"3,235",2023-10-07,occupied Palestinian territories,Gaza Strip,Khan Younis,Qizan Al-Najjar,Armed Forces of Israel,Air or Drone Strike,Crops and Lands,Agricultural Land,31.33,34.29,[2] 25km precision
164,"3,234",2023-10-07,occupied Palestinian territories,Gaza Strip,unknown,unknown,Armed Forces of Israel,Air or Drone Strike,Crops and Lands,Agricultural Land,31.52,34.51,[2] 25km precision
163,"3,233",2023-10-07,occupied Palestinian territories,Gaza Strip,North Gaza,Beit Lahia,Armed Forces of Israel,Air or Drone Strike,Crops and Lands,Agricultural Land,31.55,34.51,[2] 25km precision
162,"3,232",2023-10-07,occupied Palestinian territories,Gaza Strip,Deir el-Balah,Nuseirat Refugee Camp,Armed Forces of Israel,"Artillery, Shelling or Missile Fire",Crops and Lands,Agricultural Land,31.45,34.40,[2] 25km precision
...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,"3,335",2024-09-03,occupied Palestinian territories,Gaza Strip,Khan Younis,unknown,Armed Forces of Israel,Air or Drone Strike,Crops and Lands,Agricultural Land,31.32,34.34,[2] 25km precision
264,"3,334",2024-09-05,occupied Palestinian territories,Gaza Strip,North Gaza,unknown,Armed Forces of Israel,Air or Drone Strike,Crops and Lands,Agricultural Land,31.56,34.48,[2] 25km precision
263,"3,333",2024-09-11,occupied Palestinian territories,Gaza Strip,Gaza City,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.53,34.46,[2] 25km precision
261,"3,331",2024-09-13,occupied Palestinian territories,Gaza Strip,Gaza City,unknown,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.50,34.47,[2] 25km precision
260,"3,330",2024-09-16,occupied Palestinian territories,Gaza Strip,Khan Younis,Al Mawasi,Armed Forces of Israel,Air or Drone Strike,Food Supply Chains,Bakery,31.35,34.25,[2] 25km precision

finally, we will rename some columns to make their names easier to understand

In [41]:
df = df.rename(
    columns={
        "ID": "event_id",
        "Admin 1": "administrative_division_1",
        "Admin 2": "administrative_division_2",
        "Reported Means of Action": "Method of Attack",
    }
)
df.head()

,event_id,Date,Country,administrative_division_1,administrative_division_2,Location,Reported Perpetrator Name,Method of Attack,Object Affected,Sub-Object Affected,Latitude,Longitude,Geo-Precision
166,"3,236",2023-10-07,occupied Palestinian territories,Gaza Strip,Gaza City,Sheikh Radwan,Armed Forces of Israel,Air or Drone Strike,Crops and Lands,Agricultural Land,31.53,34.47,[2] 25km precision
165,"3,235",2023-10-07,occupied Palestinian territories,Gaza Strip,Khan Younis,Qizan Al-Najjar,Armed Forces of Israel,Air or Drone Strike,Crops and Lands,Agricultural Land,31.33,34.29,[2] 25km precision
164,"3,234",2023-10-07,occupied Palestinian territories,Gaza Strip,unknown,unknown,Armed Forces of Israel,Air or Drone Strike,Crops and Lands,Agricultural Land,31.52,34.51,[2] 25km precision
163,"3,233",2023-10-07,occupied Palestinian territories,Gaza Strip,North Gaza,Beit Lahia,Armed Forces of Israel,Air or Drone Strike,Crops and Lands,Agricultural Land,31.55,34.51,[2] 25km precision
162,"3,232",2023-10-07,occupied Palestinian territories,Gaza Strip,Deir el-Balah,Nuseirat Refugee Camp,Armed Forces of Israel,"Artillery, Shelling or Missile Fire",Crops and Lands,Agricultural Land,31.45,34.40,[2] 25km precision

In [42]:
df.to_csv(
    "../../1_datasets/data/clean_datasets/fivc_gaza_october_cleaned.csv",
    index=False,
)