
# 🧹 Dataset Cleaning Notebook

This notebook contains the steps used to clean **dataset1b**. The goal is to ensure the dataset is ready for analysis by addressing issues like missing values, duplicates, and inconsistent formatting.

We use Python's `pandas` library to handle the data cleaning tasks.


## 📥 Step 1: Load Dataset

In this step, we load the dataset into a pandas DataFrame so we can inspect and manipulate it.

In [ ]:
import pandas as pd
import json

# Load JSON file
with open('/content/gaza-displacement.json') as f:
    data = json.load(f)

# Convert to DataFrame
df = pd.DataFrame(data)
df.head()

,id,date,source,link,map_idf,map_full,map_zoom,displacement_blocks,labeled_safe_blocks,area_sq_km_displacement,area_sq_km_labeled_safe
0,119,2025-06-20,https://x.com/AvichayAdraee/status/19360336788...,https://gazamaps.com/displacement/119,https://gazamaps.com/storage/displacement-maps...,https://gazamaps.com/storage/displacement-maps...,https://gazamaps.com/storage/displacement-maps...,"606, 607, 719, 720",,0.80,0.00
1,118,2025-06-17,https://x.com/AvichayAdraee/status/19350608830...,https://gazamaps.com/displacement/118,https://gazamaps.com/storage/displacement-maps...,https://gazamaps.com/storage/displacement-maps...,https://gazamaps.com/storage/displacement-maps...,"36, 89.3, 2351, 2353, 2354, 2355, 2356",,5.37,0.00
2,117,2025-06-14,https://x.com/AvichayAdraee/status/19339369922...,https://gazamaps.com/displacement/117,https://gazamaps.com/storage/displacement-maps...,https://gazamaps.com/storage/displacement-maps...,https://gazamaps.com/storage/displacement-maps...,"46, 47, 63, 64, 99, 100, 106, 107, 108, 109",,2.82,0.00
3,116,2025-06-13,https://x.com/avichayadraee/status/19335248032...,https://gazamaps.com/displacement/116,https://gazamaps.com/storage/displacement-maps...,https://gazamaps.com/storage/displacement-maps...,https://gazamaps.com/storage/displacement-maps...,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",,257.48,0.00
4,114,2025-06-12,https://x.com/avichayadraee/status/19331299144...,https://gazamaps.com/displacement/114,https://gazamaps.com/storage/displacement-maps...,https://gazamaps.com/storage/displacement-maps...,https://gazamaps.com/storage/displacement-maps...,"606, 607, 714, 718, 719, 720, 722.1, 1803",,1.53,0.00


## 🧼 Step 2: Initial Cleaning

Here, we handle issues such as:
- Removing duplicates
- Dropping or imputing missing values
- Standardizing text data (e.g., column names or category labels)

In [ ]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       109 non-null    int64
 1   date                     109 non-null    object
 2   source                   109 non-null    object
 3   link                     109 non-null    object
 4   map_idf                  109 non-null    object
 5   map_full                 109 non-null    object
 6   map_zoom                 109 non-null    object
 7   displacement_blocks      109 non-null    object
 8   labeled_safe_blocks      109 non-null    object
 9   area_sq_km_displacement  109 non-null    object
 10  area_sq_km_labeled_safe  109 non-null    object
dtypes: int64(1), object(10)
memory usage: 9.5+ KB

id                         0
date                       0
source                     0
link                       0
map_idf                    0
map_full                   0
map_zoom                   0
displacement_blocks        0
labeled_safe_blocks        0
area_sq_km_displacement    0
area_sq_km_labeled_safe    0
dtype: int64

In [ ]:
df['date'] = pd.to_datetime(df['date'])
df['area_sq_km_displacement'] = pd.to_numeric(df['area_sq_km_displacement'], errors='coerce')
df['area_sq_km_labeled_safe'] = pd.to_numeric(df['area_sq_km_labeled_safe'], errors='coerce')

In [ ]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       109 non-null    int64
 1   date                     109 non-null    datetime64[ns]
 2   source                   109 non-null    object
 3   link                     109 non-null    object
 4   map_idf                  109 non-null    object
 5   map_full                 109 non-null    object
 6   map_zoom                 109 non-null    object
 7   displacement_blocks      109 non-null    object
 8   labeled_safe_blocks      109 non-null    object
 9   area_sq_km_displacement  109 non-null    float64
 10  area_sq_km_labeled_safe  109 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 9.5+ KB

id                         0
date                       0
source                     0
link                       0
map_idf                    0
map_full                   0
map_zoom                   0
displacement_blocks        0
labeled_safe_blocks        0
area_sq_km_displacement    0
area_sq_km_labeled_safe    0
dtype: int64

In [ ]:
# Save to JSON file
df.to_json('gaza_displacement_cleaned.json', orient='records', indent=2)

In [ ]:
from google.colab import files
files.download('gaza_displacement_cleaned.json')


## 🔍 Step 3: Final Checks and Save Cleaned Data

After cleaning, we review the dataset structure and content to ensure it's ready for further analysis or modeling. The cleaned data is then saved to a new file.