  **idmc_event_data_for_pse_cleaning**

**1. Import Libraries**

In [1]:
import pandas as pd  # noqa: F401

**2. Load the Dataset**

In [2]:
df = pd.read_csv("../../1_datasets/data/01_category_war_events_data/gaza_diplacement_orders/idmc-event-data-for-pse.csv")
df.head()

,id,country,iso3,latitude,longitude,centroid,role,displacement_type,qualifier,figure,...,source_url,locations_name,locations_coordinates,locations_accuracy,locations_type,displacement_occurred,created_at,description,link,combined_type
0,NaN,#country+name,#country+iso3,#geo+lat,#geo+lon,NaN,NaN,#event+displacement_type,#total,#affected+displaced,...,NaN,NaN,NaN,NaN,NaN,NaN,#date+created,#description,#meta+url,#cause
1,184565.0,Palestine,PSE,31.43317,34.37793,"[31.43317, 34.37793]",Recommended figure,Conflict,total,7555,...,https://www.cccmcluster.org/sites/default/file...,"Gaza Strip, Gaza Strip, Palestinian Territories","31.43317, 34.37793",Point,Origin,Displacement without preventive evacuations re...,2025-06-04T11:18:20.683882Z,"Palestine: 7,555 displacements, 28 May - 03 Ju...",https://www.cccmcluster.org/sites/default/file...,Conflict
2,184368.0,Palestine,PSE,31.43317,34.37793,"[31.43317, 34.37793]",Recommended figure,Conflict,total,22743,...,https://www.cccmcluster.org/sites/default/file...,"Gaza Strip, Gaza Strip, Palestinian Territories","31.43317, 34.37793",Point,Origin,Displacement without preventive evacuations re...,2025-05-31T10:13:43.357892Z,"Palestine: 22,743 displacements, 23 May - 27 M...",https://www.cccmcluster.org/sites/default/file...,Conflict
3,184141.0,Palestine,PSE,31.43317,34.37793,"[31.43317, 34.37793]",Recommended figure,Conflict,total,10871,...,https://www.cccmcluster.org/sites/default/file...,"Gaza Strip, Gaza Strip, Palestinian Territories","31.43317, 34.37793",Point,Origin,Displacement without preventive evacuations re...,2025-05-26T09:42:57.292879Z,"Palestine: 10,871 displacements, 22 May - 22 M...",https://www.cccmcluster.org/sites/default/file...,Conflict
4,184140.0,Palestine,PSE,31.43317,34.37793,"[31.43317, 34.37793]",Recommended figure,Conflict,total,22548,...,https://www.cccmcluster.org/sites/default/file...,"Gaza Strip, Gaza Strip, Palestinian Territories","31.43317, 34.37793",Point,Origin,Displacement without preventive evacuations re...,2025-05-26T09:38:09.819255Z,"Palestine: 22,548 displacements, 21 May - 21 M...",https://www.cccmcluster.org/sites/default/file...,Conflict

**3.Data Cleaning**

In [13]:
df = df.drop(index=0).reset_index(drop=True)
df.head()

,id,country,iso3,latitude,longitude,centroid,role,displacement_type,qualifier,figure,...,source_url,locations_name,locations_coordinates,locations_accuracy,locations_type,displacement_occurred,created_at,description,link,combined_type
0,184565.0,Palestine,PSE,31.43317,34.37793,"[31.43317, 34.37793]",Recommended figure,Conflict,total,7555,...,https://www.cccmcluster.org/sites/default/file...,"Gaza Strip, Gaza Strip, Palestinian Territories","31.43317, 34.37793",Point,Origin,Displacement without preventive evacuations re...,2025-06-04T11:18:20.683882Z,"Palestine: 7,555 displacements, 28 May - 03 Ju...",https://www.cccmcluster.org/sites/default/file...,Conflict
1,184368.0,Palestine,PSE,31.43317,34.37793,"[31.43317, 34.37793]",Recommended figure,Conflict,total,22743,...,https://www.cccmcluster.org/sites/default/file...,"Gaza Strip, Gaza Strip, Palestinian Territories","31.43317, 34.37793",Point,Origin,Displacement without preventive evacuations re...,2025-05-31T10:13:43.357892Z,"Palestine: 22,743 displacements, 23 May - 27 M...",https://www.cccmcluster.org/sites/default/file...,Conflict
2,184141.0,Palestine,PSE,31.43317,34.37793,"[31.43317, 34.37793]",Recommended figure,Conflict,total,10871,...,https://www.cccmcluster.org/sites/default/file...,"Gaza Strip, Gaza Strip, Palestinian Territories","31.43317, 34.37793",Point,Origin,Displacement without preventive evacuations re...,2025-05-26T09:42:57.292879Z,"Palestine: 10,871 displacements, 22 May - 22 M...",https://www.cccmcluster.org/sites/default/file...,Conflict
3,184140.0,Palestine,PSE,31.43317,34.37793,"[31.43317, 34.37793]",Recommended figure,Conflict,total,22548,...,https://www.cccmcluster.org/sites/default/file...,"Gaza Strip, Gaza Strip, Palestinian Territories","31.43317, 34.37793",Point,Origin,Displacement without preventive evacuations re...,2025-05-26T09:38:09.819255Z,"Palestine: 22,548 displacements, 21 May - 21 M...",https://www.cccmcluster.org/sites/default/file...,Conflict
4,184139.0,Palestine,PSE,31.43317,34.37793,"[31.43317, 34.37793]",Recommended figure,Conflict,total,41734,...,https://www.cccmcluster.org/sites/default/file...,"Gaza Strip, Gaza Strip, Palestinian Territories","31.43317, 34.37793",Point,Origin,Displacement without preventive evacuations re...,2025-05-26T09:33:56.878240Z,"Palestine: 41,734 displacements, 20 May - 20 M...",https://www.cccmcluster.org/sites/default/file...,Conflict

**4. Data Overview**

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 36 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       61 non-null     float64
 1   country                  61 non-null     object
 2   iso3                     61 non-null     object
 3   latitude                 61 non-null     object
 4   longitude                61 non-null     object
 5   centroid                 61 non-null     object
 6   role                     61 non-null     object
 7   displacement_type        61 non-null     object
 8   qualifier                61 non-null     object
 9   figure                   61 non-null     object
 10  displacement_date        61 non-null     object
 11  displacement_start_date  61 non-null     object
 12  displacement_end_date    61 non-null     object
 13  year                     61 non-null     object
 14  event_id                 61 non-null     float64
 15  event_name               61 non-null     object
 16  event_codes              0 non-null      float64
 17  event_code_types         0 non-null      float64
 18  event_start_date         61 non-null     object
 19  event_end_date           61 non-null     object
 20  category                 0 non-null      float64
 21  subcategory              0 non-null      float64
 22  type                     0 non-null      object
 23  subtype                  0 non-null      object
 24  old_id                   0 non-null      float64
 25  sources                  61 non-null     object
 26  source_url               61 non-null     object
 27  locations_name           61 non-null     object
 28  locations_coordinates    61 non-null     object
 29  locations_accuracy       61 non-null     object
 30  locations_type           61 non-null     object
 31  displacement_occurred    32 non-null     object
 32  created_at               61 non-null     object
 33  description              61 non-null     object
 34  link                     61 non-null     object
 35  combined_type            61 non-null     object
dtypes: float64(7), object(29)
memory usage: 17.3+ KB

In [15]:
df.shape

(61, 36)

In [16]:
df = df.drop(
    columns=[
        "event_codes",
        "event_code_types",
        "type",
        "subtype",
        "category",
        "subcategory",
        "old_id",
    ],
)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       61 non-null     float64
 1   country                  61 non-null     object
 2   iso3                     61 non-null     object
 3   latitude                 61 non-null     object
 4   longitude                61 non-null     object
 5   centroid                 61 non-null     object
 6   role                     61 non-null     object
 7   displacement_type        61 non-null     object
 8   qualifier                61 non-null     object
 9   figure                   61 non-null     object
 10  displacement_date        61 non-null     object
 11  displacement_start_date  61 non-null     object
 12  displacement_end_date    61 non-null     object
 13  year                     61 non-null     object
 14  event_id                 61 non-null     float64
 15  event_name               61 non-null     object
 16  event_start_date         61 non-null     object
 17  event_end_date           61 non-null     object
 18  sources                  61 non-null     object
 19  source_url               61 non-null     object
 20  locations_name           61 non-null     object
 21  locations_coordinates    61 non-null     object
 22  locations_accuracy       61 non-null     object
 23  locations_type           61 non-null     object
 24  displacement_occurred    32 non-null     object
 25  created_at               61 non-null     object
 26  description              61 non-null     object
 27  link                     61 non-null     object
 28  combined_type            61 non-null     object
dtypes: float64(2), object(27)
memory usage: 13.9+ KB

In [18]:
df["figure"] = pd.to_numeric(df["figure"], errors="coerce")
date_cols = [
    "displacement_date",
    "displacement_start_date",
    "displacement_end_date",
    "event_start_date",
    "event_end_date",
    "created_at",
]
df[date_cols] = df[date_cols].apply(pd.to_datetime, errors="coerce")

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       61 non-null     float64
 1   country                  61 non-null     object
 2   iso3                     61 non-null     object
 3   latitude                 61 non-null     object
 4   longitude                61 non-null     object
 5   centroid                 61 non-null     object
 6   role                     61 non-null     object
 7   displacement_type        61 non-null     object
 8   qualifier                61 non-null     object
 9   figure                   61 non-null     int64
 10  displacement_date        61 non-null     datetime64[ns]
 11  displacement_start_date  61 non-null     datetime64[ns]
 12  displacement_end_date    61 non-null     datetime64[ns]
 13  year                     61 non-null     object
 14  event_id                 61 non-null     float64
 15  event_name               61 non-null     object
 16  event_start_date         61 non-null     datetime64[ns]
 17  event_end_date           61 non-null     datetime64[ns]
 18  sources                  61 non-null     object
 19  source_url               61 non-null     object
 20  locations_name           61 non-null     object
 21  locations_coordinates    61 non-null     object
 22  locations_accuracy       61 non-null     object
 23  locations_type           61 non-null     object
 24  displacement_occurred    32 non-null     object
 25  created_at               61 non-null     datetime64[ns, UTC]
 26  description              61 non-null     object
 27  link                     61 non-null     object
 28  combined_type            61 non-null     object
dtypes: datetime64[ns, UTC](1), datetime64[ns](5), float64(2), int64(1), object(20)
memory usage: 13.9+ KB

In [20]:
df["latitude"] = pd.to_numeric(df["latitude"], errors="coerce")
df["longitude"] = pd.to_numeric(df["longitude"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       61 non-null     float64
 1   country                  61 non-null     object
 2   iso3                     61 non-null     object
 3   latitude                 61 non-null     float64
 4   longitude                61 non-null     float64
 5   centroid                 61 non-null     object
 6   role                     61 non-null     object
 7   displacement_type        61 non-null     object
 8   qualifier                61 non-null     object
 9   figure                   61 non-null     int64
 10  displacement_date        61 non-null     datetime64[ns]
 11  displacement_start_date  61 non-null     datetime64[ns]
 12  displacement_end_date    61 non-null     datetime64[ns]
 13  year                     61 non-null     object
 14  event_id                 61 non-null     float64
 15  event_name               61 non-null     object
 16  event_start_date         61 non-null     datetime64[ns]
 17  event_end_date           61 non-null     datetime64[ns]
 18  sources                  61 non-null     object
 19  source_url               61 non-null     object
 20  locations_name           61 non-null     object
 21  locations_coordinates    61 non-null     object
 22  locations_accuracy       61 non-null     object
 23  locations_type           61 non-null     object
 24  displacement_occurred    32 non-null     object
 25  created_at               61 non-null     datetime64[ns, UTC]
 26  description              61 non-null     object
 27  link                     61 non-null     object
 28  combined_type            61 non-null     object
dtypes: datetime64[ns, UTC](1), datetime64[ns](5), float64(4), int64(1), object(18)
memory usage: 13.9+ KB

In [24]:
# Save cleaned DataFrame to CSV (no index)
df.to_csv("cleaned_data.csv", index=False)

# The file "cleaned_data.csv" is now saved in your working directory.
# You can download it manually if needed.